# Use a lightweight JDK base image
FROM openjdk:17-jdk-slim

# Set application JAR file
ARG JAR_FILE=target/news-backend-0.0.1-SNAPSHOT.jar

# Copy the application JAR file
COPY ${JAR_FILE} app.jar

# Expose port 8080
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
